### PR TITLE
Trinchera

### PR DESCRIPTION
**Pull request by fapn91**

### CODE REVIEW

**Comment by SheenaF17** [comment]
The merge must be into the branch "new song" and not the "main" branch.

**Comment by kbjarkefur** [comment]
While you are free (and encouraged) to use these resources, you should use this [script](https://github.com/worldbank/dime-github-trainings/blob/main/GitHub-trainings/Intro-Git-GitHub-Contributor/jupyter-repo-setup/Setup%20TrainingRepo.ipynb) to set up your own repo, not work in this repo. While you can work in forks of this repo, you should not submit pull requests from forks to this repo during a training. I am therefor closing this PR.

You are of course free (and encouraged) to submit PR from forks if the intention is to improve the resources used in this repo.

Let me know if you have any questions. Happy to help.

**Comment by SheenaF17** [comment]
Hi Kristoffer,

It looks like one of our training participants accidentally tried to merge into the DIME training. We used a fork to conduct our training here at EduAnalytics so apologies for the confusion.

Best,
Sheena

**Comment by kbjarkefur** [comment]
No worries.

**Pull request closed without merging**
