### PR TITLE
Add .Rproj to gitignore

### PR DESCRIPTION
**Pull request by kbjarkefur**
@luizaandrade shoulod we un-ingnore `.Rproj` files as well? They seem handy for R on Databricks. You see any issue with doing this?

### CODE REVIEW

**Comment by kbjarkefur** [comment]
Pinging the R people @luisesanmartin @luizaandrade . Should we un-ignore the `.Rproj` file? My reading is that best practice is to commit the  `.Rproj` file in the repository (see [here](https://community.rstudio.com/t/should-rproj-files-be-added-to-gitignore/1269)) but not the `.Rproj.user` ([see here](https://github.com/rstudio/rstudio/issues/3326)). That is what the edit in this PR would do. Just merge this PR if you agree.

**Comment by luisesanmartin** [comment]
I think the argument that the `Rproj` files can set up a project easily for any repository collaborator is a strong point for not including them in `.gitignore`

**Comment by kbjarkefur** [comment]
Our ignore template ignores everything, and then un-ignore what do want to be committed. So now we un-ingore `*.Rproj` files. That is a bit of an unusual set up, but so much better (IMHO). Just wanted to make sure that that setup is clear.

**Review by luisesanmartin — APPROVED** [review]
Since adding `Rproj` to the repository allows an easy way to build the project for any contributor, I'm in favor of excluding these files from `.gitignore`

**Pull request merged**
